"""Add phrases

Revision ID: 20210104182024
Revises: 
Create Date: 2021-01-04 18:20:25.983398

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '20210104182024'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_table('phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('phrase_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_phrase_id', sa.Integer(), nullable=True),
    sa.Column('target_phrase_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_phrase_id'], ['phrases.id'], ),
    sa.ForeignKeyConstraint(['target_phrase_id'], ['phrases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_phrase_id', 'target_phrase_id', name='source_target_phrases_unique')
    )
    op.create_table('study_phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['link_id'], ['phrase_links.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'link_id', name='account_link_unique')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_phrases')
    op.drop_table('phrase_links')
    op.drop_table('phrases')
    op.drop_table('accounts')
    # ### end Alembic commands ###
