version: "3"

services:

  tests:
    build: ./galangal
    volumes:
      - ./galangal:/galangal
    command: bash -c "/usr/wait-for-it.sh --timeout=0 postgres:5432 && PYTHONPATH=apps python -m pytest --verbose --disable-warnings --cov=."
    environment:
      DEBUG: "false"
      REDIS_URL: "redis://:pass@redis:6379/0"
      DATABASE_URL: "postgresql://postgres:pass@postgres:5432/galangal"
    depends_on:
      - redis
      - postgres

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass pass --save
    ports:
      - "6380:6379"

  postgres:
    image: postgres
    restart: always
    ports:
      - "15433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: galangal
