version: "3"

services:
  web:
    build: ./galangal
    ports:
      - "5000:5000"
    volumes:
      - ./galangal:/code
    restart: always
    command: bash -c "/usr/wait-for-it.sh --timeout=0 postgres:5432 && /usr/wait-for-it.sh --timeout=0 postgres_test:5432 && alembic upgrade head && python manage_web.py"
    env_file:
      - .env
    environment:
      REDIS_URL: "redis://:pass@redis:6379/0"
      TEST_REDIS_URL: "redis://:pass@redis_test:6379/0"
      DATABASE_URL: "postgresql://postgres:pass@postgres:5432/galangal"
      TEST_DATABASE_URL: "postgresql://postgres:pass@postgres_test:5432/galangal"
    depends_on:
      - redis
      - redis_test
      - postgres
      - postgres_test

  redis:
    image: "redis:alpine"
    volumes:
      - ./data/redis:/data
    command: redis-server --requirepass pass --appendonly yes
    ports:
      - "6379:6379"

  redis_test:
    image: "redis:alpine"
    command: redis-server --requirepass pass --save
    ports:
      - "6380:6379"

  postgres:
    image: postgres
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - ./tmp/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: galangal

  postgres_test:
    image: postgres
    restart: always
    ports:
      - "15433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: galangal
