version: "3"

services:

  tests:
    build: ./galangal
    volumes:
      - ./galangal:/galangal
    command: bash -c "/usr/wait-for-it.sh --timeout=0 postgres_test:5432 && PYTHONPATH=apps python -m pytest --verbose --disable-warnings --cov=."
    env_file:
      - .env
    environment:
      REDIS_TEST_URL: "redis://:pass@redis_test:6379/0"
      DATABASE_TEST_URL: "postgresql://postgres:pass@postgres_test:5432/galangal"
    depends_on:
      - redis_test
      - postgres_test

  redis_test:
    image: "redis:alpine"
    command: redis-server --requirepass pass --save
    ports:
      - "6380:6379"

  postgres_test:
    image: postgres
    restart: always
    ports:
      - "15433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: galangal
