name: Master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create env file
      run: |
        touch .env
        cat .env
    - name: Start and tests
      run: |
        make tests
    - uses: akhileshns/heroku-deploy@v3.8.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "galangal"
        heroku_email: "oryfox@gmail.com"
        branch: "master"
