name: Master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create env file
      run: |
        touch .env
        cat .env
    - name: Start and tests
      run: |
        make tests
    - name: Create heroku auth file
      run: |
        cat >~/.netrc <<EOF
        machine api.heroku.com
            login odryfox@gmail.com
            password ${{ secrets.HEROKU_API_KEY }}
        machine git.heroku.com
            login odryfox@gmail.com
            password ${{ secrets.HEROKU_API_KEY }}
        EOF
    - name: Add remote
      run: heroku git:remote --app galangal
    - name: Remote
      run: git remote -v
    - name: Branches
      run: git --no-pager branch -va
    - name: Log
      run: git --no-pager log
    - name: Push
      run: git push heroku master:refs/heads/master
