name: Master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create env file
      run: |
        touch .env
        cat .env
    - name: Start and tests
      run: |
        make tests
    - name: Create heroku auth file
      run: |
        cat >~/.netrc <<EOF
        machine api.heroku.com
            login odryfox@gmail.com
            password ${{ secrets.HEROKU_API_KEY }}
        machine git.heroku.com
            login odryfox@gmail.com
            password ${{ secrets.HEROKU_API_KEY }}
        EOF
    - name: Cat
      run: cat ~/.netrc
    - name: Set config
      run: git config user.name "Heroku-Deploy" && git config user.email "odryfox@gmail.com"
    - name: Deploy
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: "galangal"
      run: git fetch --prune --unshallow && git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master --force
